### ISSUE TITLE
Capture all console logs on the client and post back to the main console

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#112]
_From @samhatoum on June 25, 2015 1:17_

This might be helpful?

```
this.client.log("browser", function(err, res){
  console.log(res);
  callback();
});
```

_Copied from original issue: xolvio/meteor-cucumber#146_

**Comment by SierraGolf** [comment]
currently I am using this: 

```
this.After(function () {
    var logs = browser.log('browser');

    if (logs.value.length) {
        console.log(logs.value);
    }
});
```

this allows me to see any client errors (usually that is the only thing which is logged) after test-execution, if there where any.

this works fine for me. if you however want to move this functionality into the framework it should imho behave like a pipe, constantly stream logs, instead of being like a one-time-get call.
