### ISSUE TITLE
Start Meteor from the chimp command line

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#198]
```gherkin
Feature: Start Meteor app Cucumber tests with one command

In order to tests my Meteor application with Cucumber tests
I want to start running the tests with Chimp with one command
So that I can see if my tests pass

Scenario: Start tests from Meteor app root directory
  Given I am in the directory of the Meteor app
  When I start the Meteor app cucumber testing with Chimp
  Then Chimp starts a instance of my app with a separate database
  And Chimp runs the Cucumber tests that are specified in my "tests/cucumber" directory

**Comment by Sanjo** [comment]
Feature: Start Meteor app Cucumber tests with one command

In order to tests my Meteor application with Cucumber tests
I want to start running the tests with Chimp with one command
So that I can see if my tests pass

Scenario: Start tests from Meteor app root directory
  Given I am in the directory of the Meteor app
  When I start the Meteor app cucumber testing with Chimp
  Then Chimp starts a instance of my app with a separate database
  And Chimp runs the Cucumber tests that are specified in my "tests/cucumber" directory
