### ISSUE TITLE
reversing webdriver commands not working anymore

### ISSUE THREAD

**Issue by SierraGolf** [xolvio/chimp#362]
##### Steps to reproduce the problem
* create a step which uses the reverse flag for a method, e.g. `browser.waitForExist('.nonExistingElement', 5000, true)`  for an element which is actually not existing
* use the step in a scenario

#####  Expected behaviour
the reverse flag gets passed through to webdriver and causes it to actually reverse the assertion.

#####  Actual behaviour
the reverse flag which webdriver receives is always undefined, which effectively means the command is not reversed. so when asserting on an element to not be existing one gets the following error message:
```
Error: element (.nonExistingElement) still not existing after 5000ms
```

#####  Used version
* Chimp: 0.34.0
* Node.js: v5.4.0

#####  Hints
I guess it might be related to the webdriver refactoring to support chaining of method calls and to avoid specifying the element to operate on multiple times. I also assume that the actual problem is located in the `xolvio-sync-webdriverio` code base. As double checked with the webdriver folks the `wdio-sync` library works fine with the latest webdriverio changes, see [here](https://github.com/webdriverio/webdriverio/issues/1215#issuecomment-214388922).

**Comment by samhatoum** [comment]
Will look into this, thanks for reporting

**Comment by lucetius** [comment]
it works for me

**Comment by SierraGolf** [comment]
which versions?

**Comment by lucetius** [comment]
node v5.4.0
chimp 0.34.0

**Comment by lgandecki** [comment]
I've quickly modified/hacked our training repo to test this functionality:

https://github.com/sawasawasawa/xolvioTraining/tree/issue362

There is a test that checks whether the reverse works: 

https://github.com/sawasawasawa/xolvioTraining/blob/issue362/tests/specifications/chimp-issue-362.feature

you can modify the steps here:

https://github.com/sawasawasawa/xolvioTraining/blob/issue362/tests/step_definitions/critical/chimp-issue-362-steps.js

Do npm install and then run meteor from src folder and
run chimp/tests from the main folder with ./start.sh 
to confirm.
It might have get fixed with our recent changes to xolvio-sync-webdriverio

Thanks for the bug report @SierraGolf !
