### ISSUE TITLE
maxInstances support?

### ISSUE THREAD

**Issue by billyvg** [xolvio/chimp#492]
Webdriver.io supports a configuration option `maxInstances` to run tests in parallel. I've adding this option to the `webdriverio` section of my config files, but it seems to do nothing. Is this just the case where we are not passing the option to webdriver.io, or is there a deeper reason why it's not supported?

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Chimp is a test running. Webdriver.io has a test runner of its own, which is different to chimp. It's an exclusive choice between Chimp and the webdriver.io runner I'm afraid.

**Comment by dheerajbhaskar** [comment]
@samhatoum I was looking for parallel testing as well, on my local machine.

What would you suggest? Here the options I see:
1. Write tests using chimp --watch, run multiple instances using wdio (webdriver test runner)
2. Tweak an option in chimp.js (config file at root folder) for webdriverio or selenium to get the same effect

Would I be right in saying that 2. is not possible because of the design choices made? (based on comment)[https://github.com/xolvio/chimp/issues/492#issuecomment-252693305] which would leave us with 1. , correct?

Do you see any other way one could do this?

PS: Thanks for making chimp, really liking it so far :)
