### ISSUE TITLE
setupBrowserAndDDP error

### ISSUE THREAD

**Issue by jaqua** [xolvio/chimp#513]
Suddenly chimp is not running anymore. I always started it with `chimp --ddp=http://localhost:3000 --mocha --path=tests`

Now I get this error, without changing anything on my running system:

```
[chimp][helper] setupBrowserAndDDP had error
{ [Error: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"1101.1","isDefault":true},"id":1,"name":"","origin":"://"}]
  message: 'session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid \'context\': {"auxData":{"frameId":"1101.1","isDefault":true},"id":1,"name":"","origin":"://"}',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 33,
     type: 'SessionNotCreatedException',
     message: 'A new session could not be created.',
     orgStatusMessage: 'session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid \'context\': {"auxData":{"frameId":"1101.1","isDefault":true},"id":1,"name":"","origin":"://"}\n  (Session info: chrome=54.0.2840.71)\n  (Driver info: chromedriver=2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 1.08 seconds\nBuild info: version: \'2.53.1\', revision: \'a36b8b1\', time: \'2016-06-30 17:37:03\'\nSystem info: os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.11.6\', java.version: \'1.8.0_102\'\nDriver info: org.openqa.selenium.chrome.ChromeDriver' } }
Error: session not created exception
    at Object.Future.wait (/usr/local/lib/node_modules/chimp/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:345:27)
    at initBrowser (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:161:17)
    at Object.setupBrowserAndDDP (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:215:7)
    at Context.<anonymous> (/usr/local/lib/node_modules/chimp/dist/lib/mocha/mocha-helper.js:11:15)
    at /usr/local/lib/node_modules/chimp/dist/lib/utils/fiberize.js:25:14
    - - - - -
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"1101.1","isDefault":true},"id":1,"name":"","origin":"://"}
Mocha failed
```

**Comment by derouck** [comment]
I noticed a similar error since a few days in my local set-up. And now the issue has appeared on codeship as well:

inside no mirror   --mocha --path=/home/rof/src/github.com/Project/tests --watchSource=/home/rof/src/github.com/Project/tests --singleSnippetPerFile=1 --no-source
chimpBin  /home/rof/src/github.com/Project/.scripts/node_modules/.bin/chimp
command  --ddp=http://localhost:3000 --mocha --path=/home/rof/src/github.com/Project/tests --watchSource=/home/rof/src/github.com/Project/tests --singleSnippetPerFile=1 --no-source
=> App running at: http://localhost:3000

[chimp] Running...

[chimp][helper] setupBrowserAndDDP had error
{ [Error: Connection refused]
message: 'Connection refused',
type: 'RuntimeError',
seleniumStack: 
{ status: 13,
type: 'UnknownError',
message: 'An unknown server-side error occurred while processing the command.',
orgStatusMessage: 'Connection refused' } }
Error: Connection refused
at Object.Future.wait (/home/rof/src/github.com/Project/.scripts/node_modules/fibers/future.js:449:15)
at Object.<anonymous> (/home/rof/src/github.com/Project/.scripts/node_modules/wdio-sync/build/index.js:345:27)
at initBrowser (/home/rof/src/github.com/Project/.scripts/node_modules/chimp/dist/lib/chimp-helper.js:125:15)
at Object.setupBrowserAndDDP (/home/rof/src/github.com/Project/.scripts/node_modules/chimp/dist/lib/chimp-helper.js:200:7)
at Context.<anonymous> (/home/rof/src/github.com/Project/.scripts/node_modules/chimp/dist/lib/mocha/mocha-helper.js:11:15)
at /home/rof/src/github.com/Project/.scripts/node_modules/chimp/dist/lib/utils/fiberize.js:25:14
- - - - -
Mocha failed
Chimp exited with code 2

**Comment by derouck** [comment]
But this seems to be the same as #496

**Comment by lgandecki** [comment]
@jaqua @derouck could you provide your chimp versions? both global and installed locally in your projct?

**Comment by ajlouie** [comment]
I was having a similar issue to @jaqua -- chimp was starting fine yesterday, then wouldn't even run the first test this morning. Re-installing chimp by running `npm install chimp` seemed to fix the problem. Not sure why.

**Comment by lgandecki** [comment]
I'm guessing that doing npm install chimp installed a newer version that you had before. 
But, meantime, the reason why the chimp stopped working is that your evergreen chrome silently updated itself, with a breaking update.

**Comment by jaqua** [comment]
@lgandecki 
Chimp 0.41.2
Node: 4.6.1
OS: Mac OSX El Capitan 10.11.6
Java JDK: 1.8.0_102
NPM: 3.10.8

I already tried updating, but still not working. I also tried another browser (incl. phantomjs)... same problem.

**Comment by lgandecki** [comment]
That's very weird. Sorry for the trouble! Let's try to fix this.. 
@jaqua could you show me the error you get when running with phantomjs browser?

**Comment by topleft** [comment]
@lgandecki 

here is the error I get when running with safari, which is similar error to running with chrome

Chimp 0.41.2
Node: 4.4.1
OS: Mac OSX El Capitan 10.11.6
NPM: 2.14.20

[chimp][helper] setupBrowserAndDDP had error
{ [Error: Failed to connect to SafariDriver after 10065 ms
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'peters-macbook-pro.local', ip: '10.0.1.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: driver.version: SafariDriver]
  message: 'Failed to connect to SafariDriver after 10065 ms\nBuild info: version: \'2.53.1\', revision: \'a36b8b1\', time: \'2016-06-30 17:37:03\'\nSystem info: host: \'peters-macbook-pro.local\', ip: \'10.0.1.30\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.11.6\', java.version: \'1.8.0_91\'\nDriver info: driver.version: SafariDriver',
  type: 'RuntimeError',
  seleniumStack:
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'Failed to connect to SafariDriver after 10065 ms\nBuild info: version: \'2.53.1\', revision: \'a36b8b1\', time: \'2016-06-30 17:37:03\'\nSystem info: host: \'peters-macbook-pro.local\', ip: \'10.0.1.30\', os.name: \'Mac OS X\', os.arch: \'x86_64\', os.version: \'10.11.6\', java.version: \'1.8.0_91\'\nDriver info: driver.version: SafariDriver' } }
Error: Failed to connect to SafariDriver after 10065 ms
    at Object.Future.wait (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/node_modules/wdio-sync/build/index.js:345:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/dist/lib/session-manager.js:147:21)
    at initBrowser (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:161:17)
    at Object.setupBrowserAndDDP (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:215:7)
    at /usr/local/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /usr/local/lib/node_modules/chimp/node_modules/meteor-promise/fiber_pool.js:32:39
    - - - - -
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'peters-macbook-pro.local', ip: '10.0.1.30', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: driver.version: SafariDriver

**Comment by matheus-vieira** [comment]
@lgandecki I get the same error that @jaqua and @topleft send for chrome and safari.

(right now I can't send any more info since I not on the mac, but shortly I can send)

This is the command:
`./node_modules/.bin/chimp --watch --path=./source/e2e/features`

I notice that after the chrome got updated!

Running with phantomjs works fine:
`./node_modules/.bin/chimp --watch --path=./source/e2e/features --browser=phantomjs`

**Comment by matheus-vieira** [comment]
after run `export LC_NUMERIC=en_US.UTF-8` chrome back to work 👍

**Comment by jaqua** [comment]
@lgandecki 
It is really strange. I'm doing nothing, but the error is changing. Right now I get the error:

```
## There is an issue with `node-fibers` ##
`/usr/local/lib/node_modules/chimp/node_modules/fibers/bin/darwin-x64-47/fibers.node` is missing.

Try running this to fix the issue: /usr/local/bin/node /usr/local/lib/node_modules/chimp/node_modules/fibers/build
/usr/local/lib/node_modules/chimp/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
	^

Error: Missing binary. See message above.
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/xolvio-sync-webdriverio/index.js:7:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/dist/lib/session-manager.js:40:38)
    at Module._compile (module.js:413:34)
```

**Comment by jaqua** [comment]
@lgandecki 
For me also `export LC_NUMERIC=en_US.UTF-8` fixed the problem. But I don't understand why.


Im worried about similiar issues for the future. I thought I can create a 'stable' production line, so I have to take care of every update I have to do, but now the problem occured without doing anything. So if that would have happend to my real productive application (which would be in a few weeks), the whole CI-workflow would crash. I hope you understand what I mean...

**Comment by lgandecki** [comment]
meteor npm run chimp might run a different chimp version and also within a different npm/node context.

As for stability, that's definitely something that worries us too and we spend a considerable amount of time thinking how to bulletproof chimp.

Two things to keep in mind. 
1) We use chimp in production app for almost a year now, taking care of ~14 devs every day with thousands of tests per commit, and this is the first time that it broke "being left untouched". 

2) chimp is a kind of tool that depends on and bridges a lot of separate software pieces. That's the reason to use it - otherwise you have to set all those chunks together, and I bet the integration beteween the pieces would break much more often than with chimp. It's like using circleci instead of rolling the whole solution by yourself with travis and tools alike. Travis has a potential to serve you better, but it basically requires a full time or at least a half time dev to maintain it. With chimp, we are the guys that maintain testing for you - sometimes we fail, but in general, I'd like to believe, we provide a stable and useful service. More than that - since chimp is open source, you'd have a similar chance to fix the problem, than you would have with your own solution. :-) 
This time the connection between Chimp and Chrome is faulty. The bug didn't affect just us, but the whole chromedriver users community - https://bugs.chromium.org/p/chromedriver/issues/detail?id=1552 . It's reasonable to suspect, that if you carefully set up all the pieces yourself instead of using chimp - you would end up having the same problem.

**Comment by jaqua** [comment]
Today everything broke again. After doing `export LC_NUMERIC=en_US.UTF-8` again, everything is working again. Just info...

**Comment by topleft** [comment]
A combination of setting the environment variable `export LC_NUMERIC=en_US.UTF-8` and uninstalling then reinstalling chimp works for me. 

In some cases the java version needs updating, you will know if you get a ECCON error or are prompted by Java to update. We had some success updating the JRE/JDK but not in all cases. 

Most effective solution for us was to uninstall Java JRE/JDK and reinstall. And then uninstall/ reinstall chimp.

**Comment by sagannotcarl** [comment]
Using the `meteor npm run chimp` command fixed it for me also. It downloaded a new selenium-standalone version the first time I ran it (I had been running chimp commands directly for a while), so I must have been using a different selenium-standalone version.

**Comment by samhatoum** [comment]
It looks like this issue has resolved itself for most people as it's an external chromedriver issue. Let me know if you need me to reopen.

Also, the latest chimp no longer uses Selenium & Java for the default chrome setup. Instead, it uses chromedriver directly.

**Comment by tomaszzar** [comment]
I'm having the same problem as described above and it seems none of the solutions proposed above work for me : / so any other ideas would be really appreciated : )

* Chimp command line used: 
```
chimp .config\chimp.js --ddp=http://localhost:3000
```
* Chimp config file: 
```
module.exports = {  
// - - - - WEBDRIVER-IO  - - - -
  webdriverio: {
    desiredCapabilities: {},
    logLevel: 'silent',
    // logOutput: null,
    host: '127.0.0.1',
    port: 4444,
    path: '/wd/hub',
    baseUrl: null,
    coloredLogs: true,
    screenshotPath: null,
    waitforTimeout: 10000,
    waitforInterval: 250,
  },
}
```
* Chimp: 0.9.4
* Node.js: v5.11.0
* Java:
 java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
* Operation system: Windows_NT 10.0.10586

#####  Console / Log Output

```
[chimp] Running...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: Connection reset]
  message: 'Connection reset',
  type: 'RuntimeError',
  seleniumStack:
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'Connection reset' } }
Error: Connection reset
    at Object.Future.wait (c:\Program Files\node_modules\fibers\future.js:449:15)
    at Object.<anonymous> (c:\Program Files\node_modules\wdio-sync\build\index.js:345:27)
    at initBrowser (c:\Program Files\node_modules\chimp\dist\lib\chimp-helper.js:168:17)
    at Object.setupBrowserAndDDP (c:\Program Files\node_modules\chimp\dist\lib\chimp-helper.js:226:7)
    at c:\Program Files\node_modules\chimp\dist\lib\cucumberjs\hooks.js:21:24
    at c:\Program Files\node_modules\meteor-promise\fiber_pool.js:33:40
    - - - - -
    at new RuntimeError (c:\Program Files\node_modules\webdriverio\build\lib\utils\ErrorHandler.js:115:12)
    at Request._callback (c:\Program Files\node_modules\webdriverio\build\lib\utils\RequestHandler.js:257:39)
    at Request.self.callback (c:\Program Files\node_modules\webdriverio\node_modules\request\request.js:373:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (c:\Program Files\node_modules\webdriverio\node_modules\request\request.js:1318:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (c:\Program Files\node_modules\webdriverio\node_modules\request\request.js:1266:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Cucumber steps failed
```
