### ISSUE TITLE
connecting via DDP error while using phantomjs

### ISSUE THREAD

**Issue by jaqua** [xolvio/chimp#525]
I'm trying to run chimp with phantomjs

	meteor npm run chimp-terminal

which will call `chimp --ddp=http://localhost:3000 --mocha --path=tests --browser=phantomjs`

This is the error I get:

	[chimp][helper] connecting via DDP error { [Error: connect ECONNREFUSED 127.0.0.1:3000]
	  code: 'ECONNREFUSED',
	  errno: 'ECONNREFUSED',
	  syscall: 'connect',
	  address: '127.0.0.1',
	  port: 3000 }

Chimp 0.41.1
Node: 4.6.1
OS: Mac OSX El Capitan 10.11.6
Java JDK: 1.8.0_102
NPM: 3.10.8

---
*Note*
If I'm runnig `chimp --ddp=http://localhost:3000 --mocha --path=tests --browser=phantomjs` directly, I get this error:

```
## There is an issue with `node-fibers` ##
`/usr/local/lib/node_modules/chimp/node_modules/fibers/bin/darwin-x64-47/fibers.node` is missing.

Try running this to fix the issue: /usr/local/bin/node /usr/local/lib/node_modules/chimp/node_modules/fibers/build
/usr/local/lib/node_modules/chimp/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
```

Don't even understand why I'm getting two different results for the same thing...

---

Running `meteor npm run chimp` (`chimp --ddp=http://localhost:3000 --mocha --path=tests`) gives me this:

	[chimp][helper] setupBrowserAndDDP had error
	{ [Error: Connection refused]
	  message: 'Connection refused',
	  type: 'RuntimeError',
	  seleniumStack: 
	   { status: 13,
	     type: 'UnknownError',
	     message: 'An unknown server-side error occurred while processing the command.',
	     orgStatusMessage: 'Connection refused' } }

Hope all these infos help you...

**Comment by samhatoum** [comment]
When using `meteor npm run` you use the same version of node/npm that Meteor uses.
When using `npm run` you use your system version of node/npm

If you installed Chimp with one, but then ran with another then that explains the fibers issue since it's native code that's built specific to a node version.

You just need to be consistent by using the same node version to install and to run Chimp.

Also, the DDP error you're getting is because you need run Meteor before you run Chimp, otherwise the DDP connection won't connect.

HTH
