### ISSUE TITLE
Is it possible to do cross-browser parallel testing with Chimp?

### ISSUE THREAD

**Issue by Windso** [xolvio/chimp#658]
I see from [this thread](https://github.com/xolvio/chimp/issues/350) it looks like Selenium Grid works just fine with Chimp. Does that mean it's possible to run tests in parallel? There doesn't seem to be any sort of documentation about this. Has anyone ever done this before?

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Yes it's possible and it's more of a question for webdriver.io rather than chimp.

The problem you'll face is state. This means that if each browser needs to have its own application state, you need to manage that. For example, you can have different environments for each browser session, or some other way to manage the state problem
